export const Users = [
    {
      id:1,
      profilePicture: "asset/person/1.jpeg",
      username: "Akash kashpay",
    },
    {
      id:2,
      profilePicture: "asset/person/2.jpeg",
      username: "Priya",
    },
    {
      id:3,
      profilePicture: "asset/person/3.jpeg",
      username: "Nikhil sharma",
    },
    {
      id:4,
      profilePicture: "asset/person/4.jpeg",
      username: "Rasool",
    },
    {
      id:5,
      profilePicture: "asset/person/5.jpeg",
      username: "Akuu",
    },
    {
      id:6,
      profilePicture: "asset/person/6.jpeg",
      username: "Divya Sharma",
    },
    {
      id:7,
      profilePicture: "asset/person/ak.jpeg",
      username: "Akanksha Maurya",
    },
    {
      id:8,
      profilePicture: "asset/person/7.jpeg",
      username: "Akash Maurya",
    },
    {
      id:9,
      profilePicture: "asset/person/8.jpeg",
      username: "Gourav",
    },
    {
      id:10,
      profilePicture: "asset/person/9.jpeg",
      username: "Mrs Maurya",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "asset/person/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "asset/person/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "asset/person/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "asset/person/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "asset/person/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "asset/person/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "asset/person/ak.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "asset/person/7.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "asset/person/8.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "asset/person/9.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];